packages:
  - docs
  - packages/*
onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sqlite3
  - unrs-resolver
overrides:
  '@waline-tscf/api': workspace:*
  '@waline-tscf/client': workspace:*
  '@waline-tscf/server': workspace:*
  '@waline-tscf/admin': workspace:*
  '@waline-tscf/cloudbase': workspace:*
  '@waline-tscf/hexo-next': workspace:*
