name: Issue Check Inactive

on: {}

jobs:
  issue-check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-inactive'
          inactive-label: 'Inactive'
          inactive-day: 30
